
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 28 10:37:19 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int diferenteA = 19;
  public static final int bool = 5;
  public static final int mayorQue = 12;
  public static final int suma = 7;
  public static final int resta = 8;
  public static final int imprimir = 23;
  public static final int igual = 6;
  public static final int letra = 33;
  public static final int string = 4;
  public static final int comillaDoble = 25;
  public static final int menorQue = 11;
  public static final int menorIgual = 13;
  public static final int si = 31;
  public static final int mientras = 37;
  public static final int numero = 34;
  public static final int EOF = 0;
  public static final int producto = 10;
  public static final int mayorIgual = 14;
  public static final int verdadero = 20;
  public static final int error = 1;
  public static final int entero = 2;
  public static final int finLinea = 22;
  public static final int llaveC = 29;
  public static final int llaveA = 28;
  public static final int falso = 21;
  public static final int y = 15;
  public static final int tipoStr = 36;
  public static final int o = 16;
  public static final int parentesisC = 27;
  public static final int numeroDecimal = 35;
  public static final int igualA = 18;
  public static final int parentesisA = 26;
  public static final int comillaSimple = 24;
  public static final int funcMain = 30;
  public static final int division = 9;
  public static final int no = 17;
  public static final int decimal = 3;
  public static final int sino = 32;
}

