
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 12 03:21:39 CST 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int diferenteA = 21;
  public static final int bool = 5;
  public static final int mayorQue = 12;
  public static final int suma = 7;
  public static final int resta = 8;
  public static final int imprimir = 25;
  public static final int coma = 39;
  public static final int igual = 6;
  public static final int letra = 35;
  public static final int string = 4;
  public static final int comillaDoble = 26;
  public static final int menorQue = 11;
  public static final int menorIgual = 13;
  public static final int si = 32;
  public static final int numero = 36;
  public static final int EOF = 0;
  public static final int producto = 10;
  public static final int mayorIgual = 14;
  public static final int verdadero = 22;
  public static final int error = 1;
  public static final int entero = 2;
  public static final int finLinea = 24;
  public static final int punto = 16;
  public static final int llaveC = 30;
  public static final int llaveA = 29;
  public static final int falso = 23;
  public static final int y = 17;
  public static final int tipoStr = 38;
  public static final int cicloMientras = 34;
  public static final int o = 18;
  public static final int parentesisC = 28;
  public static final int numeroDecimal = 37;
  public static final int igualA = 20;
  public static final int parentesisA = 27;
  public static final int comillaSimple = 15;
  public static final int funcMain = 31;
  public static final int division = 9;
  public static final int no = 19;
  public static final int decimal = 3;
  public static final int sino = 33;
}

